# Generated by Django 2.1.1 on 2018-09-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Contract')),
                ('number', models.CharField(blank=True, max_length=200, verbose_name='Frame Contract Number')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('expenditure', models.CharField(blank=True, choices=[('', 'unknown'), ('c', 'CAPEX'), ('o', 'OPEX')], max_length=1, verbose_name='Expenditure')),
                ('subject', models.CharField(blank=True, choices=[('', 'unknown'), ('hw', 'Hardware'), ('sw', 'Software'), ('ps', 'Service')], max_length=2, verbose_name='Subject')),
            ],
        ),
    ]
