# Generated by Django 2.1.1 on 2018-10-01 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20181001_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contracts.Vendor', verbose_name='Vendor'),
        ),
        migrations.AddField(
            model_name='singleinvoice',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contracts.Vendor', verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.Contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.Contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='Invoice 2018-10-01_11:46', max_length=200, verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='singleinvoice',
            name='name',
            field=models.CharField(default='Invoice 2018-10-01_11:46', max_length=200, verbose_name='Single Invoice'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact',
            field=models.TextField(blank=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Vendor'),
        ),
    ]
