# Generated by Django 2.1.1 on 2018-10-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20181001_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='description',
        ),
        migrations.RemoveField(
            model_name='singleinvoice',
            name='description',
        ),
        migrations.AddField(
            model_name='budget',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='contract',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='singleinvoice',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='Invoice 2018-10-01_12:36', max_length=200, verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='singleinvoice',
            name='name',
            field=models.CharField(default='Invoice 2018-10-01_12:36', max_length=200, verbose_name='Single Invoice'),
        ),
    ]
