# Generated by Django 2.1.1 on 2018-10-01 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20181001_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='valid_from',
            field=models.DateField(default=datetime.datetime(2018, 10, 1, 16, 53, 43, 209513, tzinfo=utc), verbose_name='Begin date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='Invoice 2018-10-01_16:53', max_length=200, verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='singleinvoice',
            name='name',
            field=models.CharField(default='Invoice 2018-10-01 16:53', max_length=200, verbose_name='Single Invoice'),
        ),
    ]
