# Generated by Django 2.1.2 on 2018-10-02 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20181001_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date of invoice'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Begin date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='Invoice', max_length=200, verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='singleinvoice',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Single Invoice'),
        ),
    ]
