# Generated by Django 2.1.2 on 2018-10-02 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_auto_20181002_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleinvoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date of invoice'),
        ),
        migrations.AlterField(
            model_name='singleinvoice',
            name='name',
            field=models.CharField(default='Invoice', max_length=200, verbose_name='Invoice'),
        ),
    ]
