# Generated by Django 2.1.2 on 2018-10-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_auto_20181004_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.Contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.Vendor', verbose_name='Vendor'),
        ),
    ]
