# Generated by Django 2.1.2 on 2018-10-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_auto_20181010_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedocument',
            old_name='document',
            new_name='pdf',
        ),
    ]
