# Generated by Django 2.1.2 on 2018-10-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_auto_20181010_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedocument',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
    ]
